apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/websocket-services: "{{ .Release.Name }}-gitlab"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    ingress.kubernetes.io/proxy-body-size: 500m
  name: {{ .Release.Name }}-ingress
  labels:
    app: {{ .Release.Name }}
spec:
  rules:
    - host:  {{ .Values.GITLAB_HOST }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-gitlab
              servicePort: 80
{{ if .Values.GITLAB_PAGES_DOMAIN }}
    - host: {{ .Values.GITLAB_PAGES_DOMAIN }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-gitlab
              servicePort: 80
{{ end }}
{{ if .Values.GITLAB_REGISTRY_HOST }}
    - host: {{ .Values.GITLAB_REGISTRY_HOST }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-registry
              servicePort: 5000
{{ end }}

  tls:
      - hosts:
          - {{ .Values.GITLAB_HOST }}
{{ if .Values.GITLAB_REGISTRY_HOST }}
          - {{ .Values.GITLAB_REGISTRY_HOST }}
{{ end }}
{{ if .Values.GITLAB_PAGES_DOMAIN }}
          - {{ .Values.GITLAB_PAGES_DOMAIN }}
{{ end }}
        secretName: {{ .Values.GITLAB_HOST }}-tls
