apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gitlab
  labels:
    app: {{ .Release.Name }}-gitlab
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 22
      targetPort: 22
      name: ssh
  selector:
    app: {{ .Release.Name }}-gitlab

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: {{ .Release.Name }}-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: {{ .Release.Name }}-redis

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
  labels:
    app: {{ .Release.Name }}-postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgresql
  selector:
    app: {{ .Release.Name }}-postgresql

{{ if .Values.GITLAB_REGISTRY_ENABLED }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-registry
  labels:
    app: {{ .Release.Name }}-registry
spec:
  ports:
    - port: 5000
      targetPort: 5000
      name: registry
  selector:
    app: {{ .Release.Name }}-registry
{{ end }}
